implemented basic code for bmi calculator
mupputur/pyqt_desktop_tools pull request #1
Opened 2023-04-20 02:39 UTC by Ravieruvuri

2023-04-20 16:55 UTC, dheerajkuppila approved these changes
Changes look Good .

2023-04-21 01:49 UTC, mupputur commented on bmi_calculator/bmi_calculator.py
> +class MyGUIWindow(QDialog):
The class names should be meaning full   use` BMICalWindow(QDialog`) instead of MyGUIWindow(QDialog):

2023-04-21 01:53 UTC, mupputur commented on bmi_calculator/bmi_calculator.py
> +    QWidget,
Removed unused variables or module imports.  For example, you have imported  QWidget , but not used any where

2023-04-21 01:56 UTC, mupputur commented on bmi_calculator/bmi_calculator.py
> +        self.weight = QLineEdit()
insted of `self.weight ` --> `  self.text_filed_weight`, try to updated the UI object names with clear  differentiation

2023-04-21 01:59 UTC, mupputur commented on bmi_calculator/bmi_calculator.py
> +import sys
Please provide the header format which includes ,   auther , reviewer , created  & modified date along with VDAC license  format

2023-04-21 02:03 UTC, mupputur commented on bmi_calculator/bmi_calculator.py
> +        a = QLabel("BMI is:")
What is a ?

2023-04-21 02:08 UTC, mupputur commented on bmi_calculator/bmi_calculator.py
> +            self.combo_box.addItem(str(i))
Check `addItems `function to to map the items inside combobox

2023-04-21 02:09 UTC, mupputur commented on bmi_calculator/bmi_calculator.py
> +        self.weight.clear()
Rename the function    `clear_data `with `clear_input_fields`

2023-04-21 02:11 UTC, mupputur requested changes
Please find inline comments and work with @dheerajkuppila  to fix the issues.  Please folow the PEP8 coding standards https://peps.python.org/pep-0008/

2023-04-23 03:54 UTC, mupputur approved these changes

2023-04-23 03:55 UTC, merged